#!/usr/bin/env bash

CT="Content-Type:application/json"

while true
do
curl -d '{"data": {"id":'"$((RANDOM % 1000))"'}, "timestamp": '"`date +%s`"'}' -H $CT -X POST http://localhost:3000/collect
sleep $((RANDOM % 2))
done
