const TOPIC_DATA_RECEIVED = 'data:received';
const TOPIC_DATA_FILTERED = 'data:filtered';
const TOPIC_DATA_DEDUPED = 'data:deduped';
const TOPIC_INPUT = 'data:input';
const THROTTLE_CACHE_SIZE = 5;
const THROTTLE_TIMEOUT = 3000;
const DEDUPE_INTERVAL = 10000;

module.exports = {
  TOPIC_DATA_RECEIVED,
  TOPIC_DATA_FILTERED,
  TOPIC_DATA_DEDUPED,
  TOPIC_INPUT,
  THROTTLE_CACHE_SIZE,
  THROTTLE_TIMEOUT,
  DEDUPE_INTERVAL,
};
