const TOPIC_DATA_RECEIVED = 'data:received';
const TOPIC_DATA_FILTERED = 'data:filtered';
const RECEIVER_LENGTH = 5;
const RECEIVER_TIMEOUT = 3000;

module.exports = {
  TOPIC_DATA_RECEIVED,
  TOPIC_DATA_FILTERED,
  RECEIVER_LENGTH,
  RECEIVER_TIMEOUT,
};
