const TOPIC_DATA_RECEIVED = 'data:received';
const TOPIC_DATA_FILTERED = 'data:filtered';
const TOPIC_DATA_DEDUPED = 'data:deduped';
const RECEIVER_LENGTH = 5;
const RECEIVER_TIMEOUT = 3000;
const DEDUPE_INTERVAL = 10000;

module.exports = {
  TOPIC_DATA_RECEIVED,
  TOPIC_DATA_FILTERED,
  TOPIC_DATA_DEDUPED,
  RECEIVER_LENGTH,
  RECEIVER_TIMEOUT,
  DEDUPE_INTERVAL,
};
